[package]
org = "sachinira"
name = "template_gsheet_updaterow_to_gmail"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "googleapis_sheets"
version = "0.99.7"

[[dependency]]
org = "ballerinax"
name = "googleapis_gmail"
version = "0.99.5"
